import React from "react";

export const PrintReport = React.forwardRef<HTMLDivElement, { result: any; enabled: Set<string> }>(
  ({ result, enabled }, ref) => {
    if (!result || !result.repository) return <div ref={ref} className="hidden" />;

    const repo = result.repository;
    const stats = result.stats || {};
    const techStack = result.tech_stack || {};
    const files = result.files || [];
    const contributors = result.contributors || [];

    // Format the date
    const formatDate = (dateStr: string) =>
      dateStr ? new Date(dateStr).toLocaleDateString() : "N/A";

    return (
      <div
        ref={ref}
        className="absolute left-[-9999px] top-[-9999px] w-[800px] bg-white text-black print-container"
        style={{ fontFamily: "Arial, sans-serif" }}
      >
        {/* Cover Page */}
        <div className="flex h-[1100px] flex-col items-center justify-center p-12 text-center bg-slate-50">
          <h1 className="mb-4 text-5xl font-bold text-slate-900">Repository Analysis Report</h1>
          <h2 className="mb-2 text-3xl font-semibold text-teal-600">{repo.name}</h2>
          <p className="text-xl text-slate-500">by {repo.owner}</p>
          
          <div className="mt-16 w-full max-w-lg rounded-xl border border-slate-200 bg-white p-8 shadow-sm">
            <h3 className="mb-4 text-xl font-bold text-slate-800">Quick Stats</h3>
            <div className="grid grid-cols-2 gap-4 text-left">
              <div className="flex flex-col"><span className="text-sm text-slate-500">Stars</span><span className="text-lg font-semibold">{repo.stars || 0}</span></div>
              <div className="flex flex-col"><span className="text-sm text-slate-500">Forks</span><span className="text-lg font-semibold">{repo.forks || 0}</span></div>
              <div className="flex flex-col"><span className="text-sm text-slate-500">Files</span><span className="text-lg font-semibold">{stats.files || 0}</span></div>
              <div className="flex flex-col"><span className="text-sm text-slate-500">Lines of Code</span><span className="text-lg font-semibold">{stats.loc || 0}</span></div>
              <div className="flex flex-col"><span className="text-sm text-slate-500">Created</span><span className="text-lg font-semibold">{formatDate(repo.created_at)}</span></div>
              <div className="flex flex-col"><span className="text-sm text-slate-500">Last Updated</span><span className="text-lg font-semibold">{formatDate(repo.updated_at)}</span></div>
            </div>
          </div>
          
          <p className="mt-auto text-sm text-slate-400">Generated by CodeBase Explainer</p>
        </div>

        <div className="p-12 space-y-16">
          
          {enabled.has("overview") && (
            <section className="mb-12">
              <h2 className="mb-6 border-b-2 border-teal-500 pb-2 text-2xl font-bold text-slate-800">1. Overview</h2>
              <p className="mb-4 text-slate-700">{repo.description || "No description provided for this repository."}</p>
              
              {repo.topics && repo.topics.length > 0 && (
                <div className="mb-6">
                  <h3 className="mb-2 font-semibold text-slate-800">Topics:</h3>
                  <div className="flex flex-wrap gap-2">
                    {repo.topics.map((t: string) => (
                      <span key={t} className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">{t}</span>
                    ))}
                  </div>
                </div>
              )}
              
              <div className="grid grid-cols-2 gap-6">
                <div className="rounded-lg border border-slate-200 p-4">
                  <h3 className="mb-2 font-semibold text-slate-800">Languages</h3>
                  <ul className="space-y-1">
                    {Object.entries(result.languages || {}).map(([lang, bytes]: [string, any]) => (
                      <li key={lang} className="flex justify-between text-sm">
                        <span className="text-slate-600">{lang}</span>
                        <span className="font-medium">{bytes} bytes</span>
                      </li>
                    ))}
                  </ul>
                </div>
                
                <div className="rounded-lg border border-slate-200 p-4">
                  <h3 className="mb-2 font-semibold text-slate-800">Activity</h3>
                  <ul className="space-y-1 text-sm">
                    <li className="flex justify-between"><span className="text-slate-600">Open Issues:</span><span className="font-medium">{repo.open_issues || 0}</span></li>
                    <li className="flex justify-between"><span className="text-slate-600">Default Branch:</span><span className="font-medium">{repo.default_branch}</span></li>
                    <li className="flex justify-between"><span className="text-slate-600">Total Branches:</span><span className="font-medium">{stats.branches || 0}</span></li>
                    <li className="flex justify-between"><span className="text-slate-600">Contributors:</span><span className="font-medium">{stats.contributors || 0}</span></li>
                  </ul>
                </div>
              </div>
            </section>
          )}

          {enabled.has("tech_stack") && (
            <section className="mb-12">
              <h2 className="mb-6 border-b-2 border-teal-500 pb-2 text-2xl font-bold text-slate-800">2. Tech Stack & Dependencies</h2>
              
              {techStack.frameworks && techStack.frameworks.length > 0 && (
                <div className="mb-6">
                  <h3 className="mb-3 text-lg font-semibold text-slate-800">Detected Frameworks</h3>
                  <div className="flex flex-wrap gap-2">
                    {techStack.frameworks.map((f: string) => (
                      <span key={f} className="rounded-md bg-teal-50 px-3 py-1.5 text-sm font-medium text-teal-700 border border-teal-200">
                        {f}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <h3 className="mb-3 text-lg font-semibold text-slate-800">Project Dependencies</h3>
              <div className="overflow-hidden rounded-lg border border-slate-200">
                <table className="w-full text-left text-sm">
                  <thead className="bg-slate-50 text-slate-700">
                    <tr>
                      <th className="px-4 py-3 font-semibold">Package Name</th>
                      <th className="px-4 py-3 font-semibold">Version Requirement</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {Object.entries(result.dependencies || {}).map(([pkg, ver]: [string, any]) => (
                      <tr key={pkg} className="hover:bg-slate-50">
                        <td className="px-4 py-2 font-medium text-slate-800">{pkg}</td>
                        <td className="px-4 py-2 text-slate-600 font-mono text-xs">{ver}</td>
                      </tr>
                    ))}
                    {Object.keys(result.dependencies || {}).length === 0 && (
                      <tr>
                        <td colSpan={2} className="px-4 py-8 text-center text-slate-500">No dependencies found</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {enabled.has("tree_structure") && (
            <section className="mb-12">
              <h2 className="mb-6 border-b-2 border-teal-500 pb-2 text-2xl font-bold text-slate-800">3. Project Tree Structure</h2>
              <div className="rounded-lg border border-slate-200 bg-slate-50 p-6">
                <div className="font-mono text-xs leading-relaxed text-slate-700 whitespace-pre-wrap columns-2 gap-8">
                  {files.slice(0, 150).map((f: any, i: number) => (
                    <div key={i} className="truncate">
                      {f.path}
                    </div>
                  ))}
                  {files.length > 150 && (
                    <div className="mt-2 text-slate-500 italic">...and {files.length - 150} more files</div>
                  )}
                </div>
              </div>
            </section>
          )}

          {enabled.has("summaries") && (
            <section className="mb-12">
              <h2 className="mb-6 border-b-2 border-teal-500 pb-2 text-2xl font-bold text-slate-800">4. Codebase Summaries</h2>
              <p className="mb-4 text-slate-700">
                This repository, <strong className="text-teal-600">{repo.name}</strong>, is primarily written in {Object.keys(result.languages || {})[0] || 'various languages'}.
                It consists of {stats.files || 0} files totaling {stats.loc || 0} bytes of code.
              </p>
              
              <h3 className="mt-6 mb-3 text-lg font-semibold text-slate-800">Recent Commits</h3>
              <div className="space-y-3">
                {(result.commits || []).slice(0, 10).map((commit: any, i: number) => (
                  <div key={i} className="flex flex-col rounded-lg border border-slate-200 p-3">
                    <span className="font-medium text-slate-800 text-sm truncate">{commit.message}</span>
                    <div className="mt-1 flex justify-between text-xs text-slate-500">
                      <span>{commit.author}</span>
                      <span>{formatDate(commit.date)}</span>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {enabled.has("graph") && (
            <section className="mb-12">
              <h2 className="mb-6 border-b-2 border-teal-500 pb-2 text-2xl font-bold text-slate-800">5. Graph / Contributor Analysis</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h3 className="mb-3 font-semibold text-slate-800">Top Contributors</h3>
                  <div className="space-y-2">
                    {contributors.slice(0, 8).map((c: any, i: number) => (
                      <div key={i} className="flex items-center justify-between rounded-lg border border-slate-200 p-2">
                        <div className="flex items-center gap-2 text-sm font-medium">
                          <span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-100 text-slate-600 text-xs">
                            {i + 1}
                          </span>
                          {c.login}
                        </div>
                        <span className="rounded bg-teal-50 px-2 py-0.5 text-xs font-semibold text-teal-700 border border-teal-100">
                          {c.contributions} commits
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
                
                <div>
                  <h3 className="mb-3 font-semibold text-slate-800">Repository Network</h3>
                  <div className="rounded-lg border border-slate-200 bg-slate-50 p-6 flex flex-col items-center justify-center h-[300px] text-center">
                    <p className="text-slate-500 text-sm mb-4">Network Graph Visualization Data</p>
                    <div className="flex flex-wrap justify-center gap-2 opacity-60">
                      <span className="rounded-full border border-slate-300 bg-white px-3 py-1 text-xs">Nodes: {files.length}</span>
                      <span className="rounded-full border border-slate-300 bg-white px-3 py-1 text-xs">Links: {files.length > 0 ? files.length - 1 : 0}</span>
                      <span className="rounded-full border border-slate-300 bg-white px-3 py-1 text-xs">Components: {techStack.frameworks?.length || 0}</span>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          )}

          <div className="mt-20 border-t border-slate-200 pt-8 text-center text-sm text-slate-400">
            End of Report
          </div>
        </div>
      </div>
    );
  }
);
