MAX_REPOSITORY_SIZE_MB = 150

MAX_FILE_SIZE_MB = 2
MAX_CHUNK_TOKENS = 2000

MAX_FILE_TOKENS = 12000

SUMMARY_BATCH_SIZE = 5

MAX_CONCURRENT_SUMMARIES = 3

IGNORED_PATTERNS = [
    ".min.js",
    ".bundle.js",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
]

GENERATED_FILE_HINTS = [
    "@generated",
    "auto-generated",
    "generated by",
]
IGNORED_DIRECTORIES = {
    ".git",
    "node_modules",
    "dist",
    "build",
    ".next",
    "__pycache__",
    ".venv",
    "venv",
    "coverage",
    ".idea",
    ".vscode",
}

IGNORED_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".mp4",
    ".mov",
    ".zip",
    ".tar",
    ".gz",
    ".exe",
    ".dll",
    ".so",
    ".pdf",
    ".woff",
    ".woff2",
}

PACKAGE_FILES = {
    "package.json",
    "requirements.txt",
    "pyproject.toml",
    "Pipfile",
    "poetry.lock",
    "composer.json",
    "Cargo.toml",
    "go.mod",
}